### ISSUE TITLE
Privacy policy solicitation will no longer pop up when Android starts for the first time

### ISSUE THREAD

**Issue by xandro0777** [siyuan-note/siyuan#10348]
License agreement displayed in Chinese?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After installation when I open the app on Android I am asked to accept or decline something written in Chinese script.

### Expected result

The text should be displayed in English, possibly other languages depending on user preference.

As a last resort a link to some online transportation should be offered.

### Version environment

```markdown
Android 13
```

### Log file

probably irrelevant, additional information available upon teq

**Comment by licaon-kter** [comment]
Oh, c'mon... that EULA on start makes the app non-FOSS... you are removing even freedom 0: run the app

IF the EULA is ONLY about some cloud services do pop-up the ACCEPT/DECLINE dialogue there... else, at the moment the app is not able to stay in F-Droid.

**Comment by 88250** [comment]
Hello, the first time the app is launched, a privacy policy request pops up (not the end user agreement, the user agreement refer to [here](https://b3log.org/siyuan/en/eula.html). This privacy policy solicitation is necessary for the online application market in the Chinese Mainland.

But because we didn't have much energy to pack separately before, it caused this confusion. We are very sorry. We will consider packaging separately to remove this unnecessary dialog box in the future. Thank you.

**Comment by 88250** [comment]
Starting from the next version, we will package it separately. Thank you for your feedback.
