### ISSUE TITLE
Release Aarch64 Linux Appimage/tar ball

### ISSUE THREAD

**Issue by ex3mpted** [siyuan-note/siyuan#10504]
### In what scenarios do you need this feature?

Linux on ARM has been growing, especially when it comes to SBCs, would love to be able to use this app on such devices as well.

### Describe the optimal solution

Release a build for linux aarch64 tar and appimage

**Comment by 88250** [comment]
Hello, we do not have the hardware environment for this architecture, so we cannot compile and release it.

Maybe you can consider helping SiYuan improve the dev version packaging script https://github.com/siyuan-note/siyuan/blob/master/.github/workflows/cd.yml so that it can be published through GitHub Actions, thank you.
