### ISSUE TITLE
移动端退出后丢失阅读进度。

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如我现在在阅读一篇文章，我阅读到一半的时候彻底退出软件，再点进去，该文章需要从头开始阅读。

### Expected result

希望打开软件或者文档能够自动跳转到最后一次阅读的位置

### Version environment

```markdown
- Version: 3.02
- Operating System: 安卓
- Browser (if used):
```

### Log file

无无无无无无无无

**Comment by 88250** [comment]
我这里测试可以保留。是通过右侧栏中的 退出应用 退出的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月9日(周六) 晚上6:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 移动端退出后丢失阅读进度。 (Issue #10555)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
例如我现在在阅读一篇文章，我阅读到一半的时候彻底退出软件，再点进去，该文章需要从头开始阅读。
 
Expected result
 
希望打开软件或者文档能够自动跳转到最后一次阅读的位置
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version: 3.02 - Operating System: 安卓 - Browser (if used):
 
Log file
 
无无无无无无无无
 
More information
 
No response

**Comment by QQQOrange** [comment]
> 我这里测试可以保留。是通过右侧栏中的 退出应用 退出的吗？
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年3月9日(周六) 晚上6:31
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [siyuan-note/siyuan] 移动端退出后丢失阅读进度。 (Issue #10555)
> 
> 
> 
> 
>  
> Is there an existing issue for this?
>   
>  I have searched the existing issues
>   
> Can the issue be reproduced with the default theme (daylight/midnight)?
>   
>  I was able to reproduce the issue with the default theme
>   
> Could the issue be due to extensions?
>   
>  I've ruled out the possibility that the extension is causing the problem.
>   
> Describe the problem
>  
> 例如我现在在阅读一篇文章，我阅读到一半的时候彻底退出软件，再点进去，该文章需要从头开始阅读。
>  
> Expected result
>  
> 希望打开软件或者文档能够自动跳转到最后一次阅读的位置
>  
> Screenshot or screen recording presentation
>  
> No response
>  
> Version environment
>  - Version: 3.02 - Operating System: 安卓 - Browser (if used):
>  
> Log file
>  
> 无无无无无无无无
>  
> More information
>  
> No response
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

不是的，是通过后台的一键清理退出的。

**Comment by 88250** [comment]
要通过 退出应用 否则会出问题：比如无法保存浏览位置，Block not found，数据同步异常等。
