### ISSUE TITLE
思源ai功能的三个影响体验问题

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10651]
### In what scenarios do you need this feature?

现在的ai功能相较于之前有一点进步，但仍然有一些问题，主要以下三点
1. 首先是不能够调整随机性
2. 第二点不能关闭不需要的功能
3. 第三点，使用功能的时候不能做任何操作

这三点都是非常影响体验

### Describe the optimal solution

第一点的随机性意义重大，毕竟不同的场合需要的随机性不一样，不能全部一竿子打死

第二点的意义在于个人的快速操作，现在的ai菜单功能太多了，用不上的不想保留，用得上的也可以移出二级菜单，让操作时更方便，还可以把高频的也可以放在更易用的位置

第三点就是在于使用时的进度条等待，这是完全没有必要，完全可以在后台进行，不用影响前台操作。现在使用的过程中屏幕前的使用者像个傻子一样等着，这是可以避免。

**Comment by 88250** [comment]
前面两点应该可以通过模型和提示调整，最后一点 https://github.com/siyuan-note/siyuan/issues/10540

**Comment by QQQOrange** [comment]
> 前面两点应该可以通过模型和提示调整，最后一点 https://github.com/siyuan-note/siyuan/issues/10540

对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？
再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到，

**Comment by 88250** [comment]
是的，可以试试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651)




  
前面两点应该可以通过模型和提示调整，最后一点 #10540
  
对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？
 再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到，

**Comment by QQQOrange** [comment]
> 是的，可以试试。
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年3月19日(周二) 下午5:30
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;"State ***@***.***&gt;;
> 主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651)
> 
> 
> 
> 
>   
> 前面两点应该可以通过模型和提示调整，最后一点 #10540
>   
> 对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？
>  再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到，
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你别选择性回复啊

**Comment by QQQOrange** [comment]
> 是的，可以试试。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月19日(周二) 下午5:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651) 前面两点应该可以通过模型和提示调整，最后一点 #10540 对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？ 再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

![image](https://github.com/siyuan-note/siyuan/assets/62794181/e504a95c-15e6-43d5-8bd0-27fbcc4b4218)
像自带的这些就不能删减，例如翻译，翻译这么多，有必要吗？再就是自定义的操作，不能够放到默认操作的前面，是在最下面的

还有一点就是操作不能取消，我要是误操作了，我想按esc取消，结果完全没反应

**Comment by 88250** [comment]
暂时不考虑了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651)




  
是的，可以试试。
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2024年3月19日(周二) 下午5:30
 收件人: @.&gt;;
 抄送: @.&gt;;"State @.&gt;;
 主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651)
 
前面两点应该可以通过模型和提示调整，最后一点 #10540
 
对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？
 再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到，
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
你别选择性回复啊

**Comment by 88250** [comment]
自带的是为了方便，其他的需求等后续考虑，现在不动了，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651)




  
是的，可以试试。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月19日(周二) 下午5:30 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 思源ai功能的三个影响体验问题 (Issue #10651) 前面两点应该可以通过模型和提示调整，最后一点 #10540 对于第一点和第二点，我仍然是有有问题，例如你说的随机性是指在提示词里面添加随机性的指示吗？ 再就是关闭不需要的功能和二级菜单功能迁出。这好像没有提到， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
image.png (view on web)
 像自带的这些就不能删减，例如翻译，翻译这么多，有必要吗？再就是自定义的操作，不能够放到默认操作的前面，是在最下面的
 
还有一点就是操作不能取消，我要是误操作了，我想按esc取消，结果完全没反应

**Comment by Achuan-2** [comment]
@88250 能否设置prompt的指定上下文数呢，比如翻译、文本纠错，一般上下文为2就够了，现在貌似使用上下文会累积，浪费token
下图是utools的GPT好友插件截图
![Clip_2024-03-19_21-48-25](https://github.com/siyuan-note/siyuan/assets/60436214/f7340722-4cd8-432d-83d3-9e6a6fd45a70)

**Comment by 88250** [comment]
@Achuan-2 通过 Clear context 指令可以清理 https://github.com/siyuan-note/siyuan/issues/10255

**Comment by Achuan-2** [comment]
> @Achuan-2 通过 Clear context 指令可以清理 #10255

每次要手动清除，有点麻烦了

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/10660

**Comment by 88250** [comment]
去掉翻译后续请关注 https://github.com/siyuan-note/siyuan/issues/10669
