### ISSUE TITLE
加上样式的文本，无法作为虚拟引用，取消样式后仍然无法作为

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如我把一个名词加上了下划线，那么这个名词本身是包含有虚拟引用的，但加上下划线之后，就无法作为虚拟引用来使用了，并且当取消样式之后，它仍然是无法作为虚拟引用的
具体看视频：

https://github.com/siyuan-note/siyuan/assets/62794181/ea31f75d-361f-4ce8-a130-1b0f5ae2291a

### Expected result

希望加上样式的文本，仍然能做虚拟引用之用，并且取消样式之后还能够保持虚拟引用

### Version environment

```markdown
- Version: 3.04
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
虚拟引用仅在纯文本上生效；取消样式以后 F5 刷新试试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 加上样式的文本，无法作为虚拟引用，取消样式后仍然无法作为 (Issue #10709)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
例如我把一个名词加上了下划线，那么这个名词本身是包含有虚拟引用的，但加上下划线之后，就无法作为虚拟引用来使用了，并且当取消样式之后，它仍然是无法作为虚拟引用的
 具体看视频：
 
https://github.com/siyuan-note/siyuan/assets/62794181/ea31f75d-361f-4ce8-a130-1b0f5ae2291a
 
Expected result
 
希望加上样式的文本，仍然能做虚拟引用之用，并且取消样式之后还能够保持虚拟引用
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version: 3.04 - Operating System: win11 - Browser (if used):
 
Log file
 
无
 
More information
 
No response

**Comment by QQQOrange** [comment]
> 虚拟引用仅在纯文本上生效；取消样式以后 F5 刷新试试。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月23日(周六) 下午4:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [siyuan-note/siyuan] 加上样式的文本，无法作为虚拟引用，取消样式后仍然无法作为 (Issue #10709) Is there an existing issue for this? I have searched the existing issues Can the issue be reproduced with the default theme (daylight/midnight)? I was able to reproduce the issue with the default theme Could the issue be due to extensions? I've ruled out the possibility that the extension is causing the problem. Describe the problem 例如我把一个名词加上了下划线，那么这个名词本身是包含有虚拟引用的，但加上下划线之后，就无法作为虚拟引用来使用了，并且当取消样式之后，它仍然是无法作为虚拟引用的 具体看视频： https://github.com/siyuan-note/siyuan/assets/62794181/ea31f75d-361f-4ce8-a130-1b0f5ae2291a Expected result 希望加上样式的文本，仍然能做虚拟引用之用，并且取消样式之后还能够保持虚拟引用 Screenshot or screen recording presentation No response Version environment - Version: 3.04 - Operating System: win11 - Browser (if used): Log file 无 More information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

也是不行的，而且加上样式的文本为什么不允许虚拟引用呢

**Comment by 88250** [comment]
我这里测试取消样式以后 F5 可以恢复虚引：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/0fabd4b8-6427-4c3a-9e38-c54172f6e805)



虚拟引用设计上就仅支持纯文本，因为加了样式以后就赋予另外一层含义了，不应该将其认为是虚拟引用。
