### ISSUE TITLE
新建文档文件名不会更新

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/f0440c56-76c9-4ba5-b54c-c7094c64eccc)
在图片中可以看到，我把新建的文档已经设立好的标题，在文档树中也有了反应，但是在页签上却没有反映出来

### Expected result

希望页签也能够一起反应

### Version environment

```markdown
- Version: 3.04
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请在默认主题下重现问题。

**Comment by QQQOrange** [comment]
> 请在默认主题下重现问题。

![image](https://github.com/siyuan-note/siyuan/assets/62794181/293e0b5b-05cf-4754-9e8e-43dd56e8b7d6)
默认主题也是这样的

**Comment by 88250** [comment]
新工作空间也这样吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705)




  
请在默认主题下重现问题。
  
image.png (view on web)
 默认主题也是这样的

**Comment by QQQOrange** [comment]
> 新工作空间也这样吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月23日(周六) 中午12:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 请在默认主题下重现问题。 image.png (view on web) 默认主题也是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

不好意思，因为工作空间的具体作用我还没整明白，所以我也不知道会不会

**Comment by 88250** [comment]
新建一个工作空间试试，这样可以排除插件和代码片段等影响。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 中午1:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705)




  
新工作空间也这样吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午12:41 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 请在默认主题下重现问题。 image.png (view on web) 默认主题也是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
不好意思，因为工作空间的具体作用我还没整明白，所以我也不知道会不会

**Comment by QQQOrange** [comment]
> 新建一个工作空间试试，这样可以排除插件和代码片段等影响。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月23日(周六) 中午1:29 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 新工作空间也这样吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午12:41 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 请在默认主题下重现问题。 image.png (view on web) 默认主题也是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 不好意思，因为工作空间的具体作用我还没整明白，所以我也不知道会不会 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

新建了一个就没有这样的问题了
![image](https://github.com/siyuan-note/siyuan/assets/62794181/f68acea9-bf8b-4f3a-8e1d-b0178bed0341)

**Comment by 88250** [comment]
老工作空间上关闭插件和代码片段逐个排查一下吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 下午4:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705)




  
新建一个工作空间试试，这样可以排除插件和代码片段等影响。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午1:29 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 新工作空间也这样吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午12:41 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 请在默认主题下重现问题。 image.png (view on web) 默认主题也是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 不好意思，因为工作空间的具体作用我还没整明白，所以我也不知道会不会 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt;
  
新建了一个就没有这样的问题了
 image.png (view on web)

**Comment by QQQOrange** [comment]
> 老工作空间上关闭插件和代码片段逐个排查一下吧。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月23日(周六) 下午4:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 新建一个工作空间试试，这样可以排除插件和代码片段等影响。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午1:29 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 新工作空间也这样吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月23日(周六) 中午12:41 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] 新建文档文件名不会更新 (Issue #10705) 请在默认主题下重现问题。 image.png (view on web) 默认主题也是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 不好意思，因为工作空间的具体作用我还没整明白，所以我也不知道会不会 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 新建了一个就没有这样的问题了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的
