### ISSUE TITLE
Set default setting for Replace Type

### ISSUE THREAD

**Issue by Shina-SG** [siyuan-note/siyuan#10703]
### In what scenarios do you need this feature?

Since I usually do search and replace within code block, this feature would help me to seamlessly go around my day without having to switch code block type ON every time.

### Describe the optimal solution

Add a menu to set Replace Type in the Setting similar to Search

**Comment by 88250** [comment]
Hello, I can set this switch here and it will still be in the ON state next time:

![image](https://github.com/siyuan-note/siyuan/assets/873584/f6f5aa16-0594-4c6d-9d1b-8414fcd112cc)

Please check whether it is because of the use of query criteria. If so, you can clear the query criteria:

![image](https://github.com/siyuan-note/siyuan/assets/873584/7f663f13-acb0-4acb-aafe-58cabcd1ad21)
