### ISSUE TITLE
Improve block ref searching performance

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11951]
提高块引搜索性能

https://ld246.com/article/1720682769643

确实不快

---

描述：

> 3.1.0 已经重建索引,  使用半小时(浏览页面), 重启过几次, 检查过思源没有明显的错误和插件异常后

步骤:

任意页面上 输入 `[[` 开始创建link

#### 输入 test, 转圈3秒,才出来列表

![image.png](https://b3logfile.com/file/2024/07/image-o8zZrCy.png)

siyuan.log报错

```
E 2024/07/11 15:13:13 block_ref_query.go:381: sql query failed: near "WHERE": syntax error
E 2024/07/11 15:13:17 block_ref_query.go:381: sql query failed: near "WHERE": syntax error
E 2024/07/11 15:17:21 block_ref_query.go:381: sql query failed: near "WHERE": syntax error
E 2024/07/11 15:18:58 block_ref_query.go:381: sql query failed: near "WHERE": syntax error // 这是上面输入 test这次的
```

### 如果这时候不做任何操作, 就停留在上图的状态, I/O ,cpu 都是高负载不停

![image.png](https://b3logfile.com/file/2024/07/image-bk4X1Rc.png)

![image.png](https://b3logfile.com/file/2024/07/image-THHh6i9.png)

红框这段就是查出列表后,啥也不干的状态.

**Comment by Jiangshuon** [comment]
数据库搜索相比之前也变慢了

**Comment by Jiangshuon** [comment]
@88250 d大，是恢复周更了吗，下周应该会更新吧

**Comment by 88250** [comment]
会的，但是后面不一定周更了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 提高块引搜索性能 (Issue #11951)




 
@88250 d大，是恢复周更了吗，下周应该会更新吧

**Comment by 88250** [comment]
嗯，差不多是这样的情况。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 提高块引搜索性能 (Issue #11951)




  
会的，但是后面不一定周更了。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月11日(周四) 下午4:03 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [siyuan-note/siyuan] 提高块引搜索性能 (Issue #11951) @88250 d大，是恢复周更了吗，下周应该会更新吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
好的，我的理解是，如果有比较影响使用的bug，就尽快更。没有的话，就不周更是吧

**Comment by 88250** [comment]
> E 2024/07/11 15:18:58 block_ref_query.go:381: sql query failed: near "WHERE": syntax error // 这是上面输入 test这次的

这个报错是因为配置的 工作空间/data/.siyuan/refsearchignore 有误，里面要写 WHERE 条件子句 才能符合 SQL 语法。

**Comment by Temacc0531** [comment]
这个块引搜索优化完我这边好像没啥感知，还是刚索引完就挺快，隔天又变慢了😥
