### ISSUE TITLE
以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#12156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

## 表现区别
以前的图片块，渲染表现多了上方和下方的空白
![image](https://github.com/user-attachments/assets/209c71ba-070d-4b18-8be3-7b1a69f607b7)
现在的图片块，渲染表现没有上方和下方的空白
![image](https://github.com/user-attachments/assets/d88a34f1-5e0b-4efe-8817-c73b03ceac4f)

## 数据对比
对比两个图片块的 json 数据

以前的图片块， json 数据如下
```json
		{
			"ID": "20240731152427-ic05zgs",
			"Type": "NodeParagraph",
			"Properties": {
				"id": "20240731152427-ic05zgs",
				"updated": "20240731152429"
			},
			"Children": [
				{
					"Type": "NodeText",
					"Data": "​"
				},
				{
					"Type": "NodeImage",
					"Data": "span",
					"Properties": {
						"parent-style": "min-width: calc(100% - 0.1em);"
					},
					"Children": [
						{
							"Type": "NodeBang"
						},
						{
							"Type": "NodeOpenBracket"
						},
						{
							"Type": "NodeLinkText"
						},
						{
							"Type": "NodeCloseBracket"
						},
						{
							"Type": "NodeOpenParen"
						},
						{
							"Type": "NodeLinkDest",
							"Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png"
						},
						{
							"Type": "NodeCloseParen"
						}
					]
				},
				{
					"Type": "NodeKramdownSpanIAL",
					"Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}"
				},
				{
					"Type": "NodeText",
					"Data": "​"
				}
			]
		},
```

现在的图片块， json 数据
```json
		{
			"ID": "20240731152427-ic05zgs",
			"Type": "NodeParagraph",
			"Properties": {
				"id": "20240731152427-ic05zgs",
				"updated": "20240731153144"
			},
			"Children": [
				{
					"Type": "NodeText",
					"Data": "​"
				},
				{
					"Type": "NodeImage",
					"Data": "span",
					"Properties": {
						"parent-style": "min-width: calc(100% - 0.1em);"
					},
					"Children": [
						{
							"Type": "NodeBang"
						},
						{
							"Type": "NodeOpenBracket"
						},
						{
							"Type": "NodeLinkText"
						},
						{
							"Type": "NodeCloseBracket"
						},
						{
							"Type": "NodeOpenParen"
						},
						{
							"Type": "NodeLinkDest",
							"Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png"
						},
						{
							"Type": "NodeCloseParen"
						}
					]
				},
				{
					"Type": "NodeKramdownSpanIAL",
					"Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}"
				},
				{
					"Type": "NodeText",
					"Data": "​"
				}
			]
		},
```

二者的核心区别是：现在的图片块，去掉了 `display: block` 
因此，问题是：没有兼容以前的图片块导致。希望能兼容以前的图片块，否则用户一个个改会比较难受

### Expected result

希望兼容以前的图片块

### Version environment

```markdown
- Version: 3.1.2
- Operating System: Win11
- Browser (if used):无
```

### Log file

无

**Comment by 88250** [comment]
这个兼容不了了，只能手动调整一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月31日(周三) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
表现区别
 
以前的图片块，渲染表现多了上方和下方的空白
 image.png (view on web)
 现在的图片块，渲染表现没有上方和下方的空白
 image.png (view on web)
 
数据对比
 
对比两个图片块的 json 数据
 
以前的图片块， json 数据如下
 		{ 			"ID": "20240731152427-ic05zgs", 			"Type": "NodeParagraph", 			"Properties": { 				"id": "20240731152427-ic05zgs", 				"updated": "20240731152429" 			}, 			"Children": [ 				{ 					"Type": "NodeText", 					"Data": "​" 				}, 				{ 					"Type": "NodeImage", 					"Data": "span", 					"Properties": { 						"parent-style": "min-width: calc(100% - 0.1em);" 					}, 					"Children": [ 						{ 							"Type": "NodeBang" 						}, 						{ 							"Type": "NodeOpenBracket" 						}, 						{ 							"Type": "NodeLinkText" 						}, 						{ 							"Type": "NodeCloseBracket" 						}, 						{ 							"Type": "NodeOpenParen" 						}, 						{ 							"Type": "NodeLinkDest", 							"Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" 						}, 						{ 							"Type": "NodeCloseParen" 						} 					] 				}, 				{ 					"Type": "NodeKramdownSpanIAL", 					"Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}" 				}, 				{ 					"Type": "NodeText", 					"Data": "​" 				} 			] 		},
 
现在的图片块， json 数据
 		{ 			"ID": "20240731152427-ic05zgs", 			"Type": "NodeParagraph", 			"Properties": { 				"id": "20240731152427-ic05zgs", 				"updated": "20240731153144" 			}, 			"Children": [ 				{ 					"Type": "NodeText", 					"Data": "​" 				}, 				{ 					"Type": "NodeImage", 					"Data": "span", 					"Properties": { 						"parent-style": "min-width: calc(100% - 0.1em);" 					}, 					"Children": [ 						{ 							"Type": "NodeBang" 						}, 						{ 							"Type": "NodeOpenBracket" 						}, 						{ 							"Type": "NodeLinkText" 						}, 						{ 							"Type": "NodeCloseBracket" 						}, 						{ 							"Type": "NodeOpenParen" 						}, 						{ 							"Type": "NodeLinkDest", 							"Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" 						}, 						{ 							"Type": "NodeCloseParen" 						} 					] 				}, 				{ 					"Type": "NodeKramdownSpanIAL", 					"Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}" 				}, 				{ 					"Type": "NodeText", 					"Data": "​" 				} 			] 		},
 
二者的核心区别是：现在的图片块，去掉了 display: block
 因此，问题是：没有兼容以前的图片块导致。希望能兼容以前的图片块，否则用户一个个改会比较难受
 
Expected result
 
希望兼容以前的图片块
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version: 3.1.2 - Operating System: Win11 - Browser (if used):无
 
Log file
 
无
 
More information
 
No response

**Comment by zhoutaosheng** [comment]
> 这个兼容不了了，只能手动调整一下。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月31日(周三) 下午3:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156) Is there an existing issue for this? I have searched the existing issues Can the issue be reproduced with the default theme (daylight/midnight)? I was able to reproduce the issue with the default theme Could the issue be due to extensions? I've ruled out the possibility that the extension is causing the problem. Describe the problem 表现区别 以前的图片块，渲染表现多了上方和下方的空白 image.png (view on web) 现在的图片块，渲染表现没有上方和下方的空白 image.png (view on web) 数据对比 对比两个图片块的 json 数据 以前的图片块， json 数据如下 { "ID": "20240731152427-ic05zgs", "Type": "NodeParagraph", "Properties": { "id": "20240731152427-ic05zgs", "updated": "20240731152429" }, "Children": [ { "Type": "NodeText", "Data": "​" }, { "Type": "NodeImage", "Data": "span", "Properties": { "parent-style": "min-width: calc(100% - 0.1em);" }, "Children": [ { "Type": "NodeBang" }, { "Type": "NodeOpenBracket" }, { "Type": "NodeLinkText" }, { "Type": "NodeCloseBracket" }, { "Type": "NodeOpenParen" }, { "Type": "NodeLinkDest", "Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" }, { "Type": "NodeCloseParen" } ] }, { "Type": "NodeKramdownSpanIAL", "Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}" }, { "Type": "NodeText", "Data": "​" } ] }, 现在的图片块， json 数据 { "ID": "20240731152427-ic05zgs", "Type": "NodeParagraph", "Properties": { "id": "20240731152427-ic05zgs", "updated": "20240731153144" }, "Children": [ { "Type": "NodeText", "Data": "​" }, { "Type": "NodeImage", "Data": "span", "Properties": { "parent-style": "min-width: calc(100% - 0.1em);" }, "Children": [ { "Type": "NodeBang" }, { "Type": "NodeOpenBracket" }, { "Type": "NodeLinkText" }, { "Type": "NodeCloseBracket" }, { "Type": "NodeOpenParen" }, { "Type": "NodeLinkDest", "Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" }, { "Type": "NodeCloseParen" } ] }, { "Type": "NodeKramdownSpanIAL", "Data": "{: parent-style=\"min-width: calc(100% - 0.1em);\"}" }, { "Type": "NodeText", "Data": "​" } ] }, 二者的核心区别是：现在的图片块，去掉了 display: block 因此，问题是：没有兼容以前的图片块导致。希望能兼容以前的图片块，否则用户一个个改会比较难受 Expected result 希望兼容以前的图片块 Screenshot or screen recording presentation No response Version environment - Version: 3.1.2 - Operating System: Win11 - Browser (if used):无 Log file 无 More information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

如果兼容不了，是否可以再下一次更新程序版本的时候，帮用户全部更新到新的格式呢？

**Comment by 88250** [comment]
不行的，风险较高，还是手动调整吧。


这个之前某个版本中发布时提过。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月31日(周三) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156)




  
这个兼容不了了，只能手动调整一下。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月31日(周三) 下午3:43 收件人: @.&gt;; 抄送: @.&gt;; 主题: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156) Is there an existing issue for this? I have searched the existing issues Can the issue be reproduced with the default theme (daylight/midnight)? I was able to reproduce the issue with the default theme Could the issue be due to extensions? I've ruled out the possibility that the extension is causing the problem. Describe the problem 表现区别 以前的图片块，渲染表现多了上方和下方的空白 image.png (view on web) 现在的图片块，渲染表现没有上方和下方的空白 image.png (view on web) 数据对比 对比两个图片块的 json 数据 以前的图片块， json 数据如下 { "ID": "20240731152427-ic05zgs", "Type": "NodeParagraph", "Properties": { "id": "20240731152427-ic05zgs", "updated": "20240731152429" }, "Children": [ { "Type": "NodeText", "Data": "​" }, { "Type": "NodeImage", "Data": "span", "Properties": { "parent-style": "min-width: calc(100% - 0.1em);" }, "Children": [ { "Type": "NodeBang" }, { "Type": "NodeOpenBracket" }, { "Type": "NodeLinkText" }, { "Type": "NodeCloseBracket" }, { "Type": "NodeOpenParen" }, { "Type": "NodeLinkDest", "Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" }, { "Type": "NodeCloseParen" } ] }, { "Type": "NodeKramdownSpanIAL", "Data": "{: parent-style="min-width: calc(100% - 0.1em);"}" }, { "Type": "NodeText", "Data": "​" } ] }, 现在的图片块， json 数据 { "ID": "20240731152427-ic05zgs", "Type": "NodeParagraph", "Properties": { "id": "20240731152427-ic05zgs", "updated": "20240731153144" }, "Children": [ { "Type": "NodeText", "Data": "​" }, { "Type": "NodeImage", "Data": "span", "Properties": { "parent-style": "min-width: calc(100% - 0.1em);" }, "Children": [ { "Type": "NodeBang" }, { "Type": "NodeOpenBracket" }, { "Type": "NodeLinkText" }, { "Type": "NodeCloseBracket" }, { "Type": "NodeOpenParen" }, { "Type": "NodeLinkDest", "Data": "assets/image_MwlQ2xs-o1-20230425202149-v6gw8qp.png" }, { "Type": "NodeCloseParen" } ] }, { "Type": "NodeKramdownSpanIAL", "Data": "{: parent-style="min-width: calc(100% - 0.1em);"}" }, { "Type": "NodeText", "Data": "​" } ] }, 二者的核心区别是：现在的图片块，去掉了 display: block 因此，问题是：没有兼容以前的图片块导致。希望能兼容以前的图片块，否则用户一个个改会比较难受 Expected result 希望兼容以前的图片块 Screenshot or screen recording presentation No response Version environment - Version: 3.1.2 - Operating System: Win11 - Browser (if used):无 Log file 无 More information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
如果兼容不了，是否可以再下一次更新程序版本的时候，帮用户全部更新到新的格式呢？

**Comment by 88250** [comment]
备份后试试吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月31日(周三) 下午4:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156)




 
量太大了😅
 如果直接在代码编辑器中，全局搜索替换display: block;，然后删除它，有风险吗

**Comment by zhoutaosheng** [comment]
> 备份后试试吧。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月31日(周三) 下午4:41 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 以前的图片块，现在渲染时，图片上方和下方，多了一些空白的内容 (Issue #12156) 量太大了😅 如果直接在代码编辑器中，全局搜索替换display: block;，然后删除它，有风险吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

@88250  @TCOTC 问下，从哪个版本，修改引入这个问题的

**Comment by 88250** [comment]
@zhoutaosheng https://github.com/siyuan-note/siyuan/issues/11757#issuecomment-2177461274
