### ISSUE TITLE
点击“关闭”或者“退出应用”选项，需要等待较长时间才可以完全退出应用

### ISSUE THREAD

**Issue by LEDZB** [siyuan-note/siyuan#12221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我想要关闭程序，点击“关闭”或者“退出应用”选项后，需要等待较长时间（＞3min）才可以完全退出应用？一直显示“正在退出”
这个是否是一个bug呢？

### Expected result

希望加快关闭应用功能

### Version environment

```markdown
V3.0.17
```

### Log file

无

**Comment by 88250** [comment]
请更新到最新版后再试试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月9日(周五) 晚上6:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 点击“关闭”或者“退出应用”选项，需要等待较长时间才可以完全退出应用 (Issue #12221)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
当我想要关闭程序，点击“关闭”或者“退出应用”选项后，需要等待较长时间（＞3min）才可以完全退出应用？一直显示“正在退出”
 这个是否是一个bug呢？
 
Expected result
 
希望加快关闭应用功能
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 V3.0.17
 
Log file
 
无
 
More information
 
No response

**Comment by TCOTC** [comment]
更新到最新版之后手动在 `文档树 - 更多 - 重建索引` ，然后等几分钟索引完成

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
