### ISSUE TITLE
SiYuan on Flatpak needs more maintainers

### ISSUE THREAD

**Issue by 5l2** [siyuan-note/siyuan#12446]
### In what scenarios do you need this feature?

It was only proletarius101 who maintained [SiYuan on Flatpak](https://github.com/flathub/org.b3log.siyuan/), thanks to the work of proletarius101.

Now [the project](https://github.com/flathub/org.b3log.siyuan/) lacks maintenance and has fallen behind the main version.

### Describe the optimal solution

More contributors are needed to maintain [the project](https://github.com/flathub/org.b3log.siyuan/).

It's not a huge amount of work, as proletarius101 has already built the framework. All contributors need to do is merge the pull requests that the bot submits when it detects a version update, and test it. If something is wrong, make some changes accordingly. Packages will be built automatically by Flatpak.

I will also participate in my spare time.

**Comment by 88250** [comment]
We will pin this issue for a week before closing it, thank you.

**Comment by 88250** [comment]
@5l2 Hello, I am not familiar with Flatpak. It is better to be maintained by community contributors. Thank you.

**Comment by 88250** [comment]
We will announce this change in the next release changlog, thanks.



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 13, 2024 13:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] SiYuan on Flatpak needs more maintainers(Issue #12446)




 
@88250 Recently SiYuan Flatpak is required to use $XDG_CONFIG_HOME instead of $HOME due to the Flatpak sandbox. This is a breaking change, which will alter the workspace location for users who already installed SiYuan Flatpak.
 See: flathub/org.b3log.siyuan#47 .
 Could you request users to check out the README if they complain about this?

**Comment by 88250** [comment]
@5l2 https://github.com/siyuan-note/siyuan/issues/12768
