### ISSUE TITLE
疑问：使用 docker 部署时主菜单按钮没有内容

### ISSUE THREAD

**Issue by ejoin-cc** [siyuan-note/siyuan#12646]
疑问：使用 docker 部署时主菜单按钮没有内容

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用 docker 部署时主菜单按钮没有内容，
<img width="291" alt="image" src="https://github.com/user-attachments/assets/5abc392c-343f-407e-88c2-feeb1c0abeb8">
查看元素，toolbar__text 没有内容。
<img width="361" alt="image" src="https://github.com/user-attachments/assets/d4ad487c-f82f-4546-b13c-a3b9ce4aaeaf">
想知道这个的内容是从哪里读取的，是否和 docker 网络有关？

### Expected result

主菜单按钮应该有内容。

### Version environment

```markdown
- Version: 3.1.7
- Operating System: docker 部署
- Browser (if used): Chrome
```

### Log file

重新执行了初始化：
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/3aa250f0-d3b8-42bc-83a8-8a1c009fbbe9">

**Comment by TCOTC** [comment]
@88250 偶尔会有人这样，要不还是加个默认值？

**Comment by ejoin-cc** [comment]
> @88250 偶尔会有人这样，要不还是加个默认值？
hello，请问目前有解决方案吗

**Comment by 88250** [comment]
发一下部署命令

**Comment by ejoin-cc** [comment]
> 发一下部署命令

版本：v3.1.7
docker-compose.yml
``` 
---
version: '3'
services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx']
    user: '1000:1000'
    ports:
      - xxxx:6806
    volumes:
      - ./workspace:/siyuan/workspace
    restart: unless-stopped
```

nginx:
```
server {
    listen 443 ssl proxy_protocol;
    server_name xxxx;

    ssl_certificate xxxx;
    ssl_certificate_key xxxx;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    location / {
        proxy_pass http://localhost:xxxx;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
    location /ws {
        proxy_pass http://localhost:xxxx;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
}
```

**Comment by 88250** [comment]
挂载卷那里 /workspace 后面再加一级看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646)




  
发一下部署命令
  
版本：v3.1.7
 docker-compose.yml
 --- version: '3' services:   siyuan:     image: b3log/siyuan:latest     container_name: siyuan     command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx']     user: '1000:1000'     ports:       - xxxx:6806     volumes:       - ./workspace:/siyuan/workspace     restart: unless-stopped  
nginx:
 server {     listen 443 ssl proxy_protocol;     server_name xxxx;     ssl_certificate xxxx;     ssl_certificate_key xxxx;     ssl_session_timeout 5m;     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;     ssl_prefer_server_ciphers on;     location / {         proxy_pass http://localhost:xxxx;         proxy_set_header Host $host;         proxy_set_header X-Real-IP $proxy_protocol_addr;         proxy_set_header X-Forwarded-For $proxy_protocol_addr;         proxy_set_header Upgrade $http_upgrade;         proxy_set_header Connection $http_connection;     }     location /ws {         proxy_pass http://localhost:xxxx;         proxy_set_header Host $host;         proxy_set_header X-Real-IP $proxy_protocol_addr;         proxy_set_header X-Forwarded-For $proxy_protocol_addr;         proxy_set_header Upgrade $http_upgrade;         proxy_set_header Connection $http_connection;     } }

**Comment by ejoin-cc** [comment]
> 挂载卷那里 /workspace 后面再加一级看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月29日(周日) 晚上6:59 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 发一下部署命令 版本：v3.1.7 docker-compose.yml --- version: '3' services: siyuan: image: b3log/siyuan:latest container_name: siyuan command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx'] user: '1000:1000' ports: - xxxx:6806 volumes: - ./workspace:/siyuan/workspace restart: unless-stopped nginx: server { listen 443 ssl proxy_protocol; server_name xxxx; ssl_certificate xxxx; ssl_certificate_key xxxx; ssl_session_timeout 5m; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_prefer_server_ciphers on; location / { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } location /ws { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

类似于这样吗：
``` volumes:
      - ./data/workspace:/siyuan/workspace
```
<img width="194" alt="image" src="https://github.com/user-attachments/assets/3d151ad6-0bf3-406b-a4b4-c9108d609335">
看起来没什么变化

**Comment by 88250** [comment]
嗯，不要在根目录就行，试试看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 晚上7:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646)




  
挂载卷那里 /workspace 后面再加一级看看
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月29日(周日) 晚上6:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 发一下部署命令 版本：v3.1.7 docker-compose.yml --- version: '3' services: siyuan: image: b3log/siyuan:latest container_name: siyuan command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx'] user: '1000:1000' ports: - xxxx:6806 volumes: - ./workspace:/siyuan/workspace restart: unless-stopped nginx: server { listen 443 ssl proxy_protocol; server_name xxxx; ssl_certificate xxxx; ssl_certificate_key xxxx; ssl_session_timeout 5m; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_prefer_server_ciphers on; location / { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } location /ws { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
类似于这样吗：
       - ./data/workspace:/siyuan/workspace  image.png (view on web) 看起来没什么变化

**Comment by ejoin-cc** [comment]
> 嗯，不要在根目录就行，试试看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月29日(周日) 晚上7:16 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 挂载卷那里 /workspace 后面再加一级看看 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月29日(周日) 晚上6:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 发一下部署命令 版本：v3.1.7 docker-compose.yml --- version: '3' services: siyuan: image: b3log/siyuan:latest container_name: siyuan command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx'] user: '1000:1000' ports: - xxxx:6806 volumes: - ./workspace:/siyuan/workspace restart: unless-stopped nginx: server { listen 443 ssl proxy_protocol; server_name xxxx; ssl_certificate xxxx; ssl_certificate_key xxxx; ssl_session_timeout 5m; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_prefer_server_ciphers on; location / { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } location /ws { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; 类似于这样吗： - ./data/workspace:/siyuan/workspace image.png (view on web) 看起来没什么变化 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

```
      - ./data/workspace:/siyuan/workspace

      - /home/xxx/siyuan/data/workspace:/siyuan/workspace
```
尝试了上面这两种方式，都没有展示主菜单文本。
<img width="181" alt="image" src="https://github.com/user-attachments/assets/461c0b3a-aa89-4374-a5bb-70c9c093d940">

**Comment by 88250** [comment]
按照 README 中的路径试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 晚上7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646)




  
嗯，不要在根目录就行，试试看
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月29日(周日) 晚上7:16 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 挂载卷那里 /workspace 后面再加一级看看 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月29日(周日) 晚上6:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [siyuan-note/siyuan] 疑问：使用 docker 部署时主菜单按钮没有内容 (Issue #12646) 发一下部署命令 版本：v3.1.7 docker-compose.yml --- version: '3' services: siyuan: image: b3log/siyuan:latest container_name: siyuan command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx'] user: '1000:1000' ports: - xxxx:6806 volumes: - ./workspace:/siyuan/workspace restart: unless-stopped nginx: server { listen 443 ssl proxy_protocol; server_name xxxx; ssl_certificate xxxx; ssl_certificate_key xxxx; ssl_session_timeout 5m; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_prefer_server_ciphers on; location / { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } location /ws { proxy_pass http://localhost:xxxx; proxy_set_header Host $host; proxy_set_header X-Real-IP $proxy_protocol_addr; proxy_set_header X-Forwarded-For $proxy_protocol_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; 类似于这样吗： - ./data/workspace:/siyuan/workspace image.png (view on web) 看起来没什么变化 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
        - ./data/workspace:/siyuan/workspace       - /home/xxx/siyuan/data/workspace:/siyuan/workspace  
尝试了上面这两种方式，都没有展示主菜单文本。
 image.png (view on web)

**Comment by ejoin-cc** [comment]
> 按照 README 中的路径试试

几乎完全按照 README 的配置：
```
version: '3'
services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=xxxx']
    ports:
      - xxxx:6806
    volumes:
      - /siyuan/workspace:/siyuan/workspace
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
```

现象一样：
<img width="314" alt="image" src="https://github.com/user-attachments/assets/ad208d08-2169-4ee9-bca1-e437a3a2e326">

**Comment by 88250** [comment]
看一下 /siyuan/workspace/conf/conf.json 中 `workspaceDir` 的值

**Comment by ejoin-cc** [comment]
> 看一下 /siyuan/workspace/conf/conf.json 中 `workspaceDir` 的值

"workspaceDir": "/siyuan/workspace/",

**Comment by 88250** [comment]
代码确实有点问题，稍后调整一下看看，感谢反馈。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
