### ISSUE TITLE
Improve database view deletion interaction

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12659]
Bug: Can't delete table on "..." option

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/user-attachments/assets/dc8644eb-0b78-43c1-a9af-da6aa7c387b1

### Expected result

deletable

### Version environment

```markdown
- Version: 3.1.8
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by Macavity** [comment]
This might be intentional. At least for me it looks like the options on the right side are for the views of a table, not the database table itself. And deleting the last view wouldn't make sense maybe? 

If that is the case though, then "delete" should likely be greyed out or hidden for the last view. Have you tested if it works with multiple views?

**Comment by 88250** [comment]
This Delete button is for views, if there is only one view, it seems that the button should be disabled @Vanessa219

**Comment by zzsimplezz** [comment]
> This Delete button is for views, if there is only one view, it seems that the button should be disabled @Vanessa219

Agree ... Notion do the same ... If not, it is confusing users like bugs.

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
