### ISSUE TITLE
XSS in the tag name

### ISSUE THREAD

**Issue by claunch3r** [siyuan-note/siyuan#13168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I found an XSS vulnerability in the tag name.

Steps to reproduce:
1. Create a tag containing an XSS payload: `<img src =q onerror=prompt(8)>`
2. As a result, an XSS vulnerability is exploited

Screenshots:
![1](https://github.com/user-attachments/assets/9238a515-c34d-4497-a238-05c67a6cccb0)
![2](https://github.com/user-attachments/assets/09c1654b-b0d6-4804-854e-e39510e96f1e)

### Expected result

---

### Screenshot or screen recording presentation

---

### Version environment

```markdown
- Version: v3.1.11
- Operating System: Arch Linux
- Browser (if used): Firefox
```

### Log file

---

### More information

---

**Comment by zxkmm** [comment]
really nice point! thx!

to me, it looks quite harmless since it's pure DOM injection vuln, that the only possible entrance (the clipper chrome plugin) already filtered special char when clipping; and ofc user won't do that on purpose

however that saying that's also would be good (and harmless) to filter special char (and also all the eval injections too). not only defense this xss, but also prevent some potential bugs that can be triggered. so still a nice point.

@Vanessa219
