### ISSUE TITLE
How can Siyuan synchronize notes through third-party software after Android 11?

### ISSUE THREAD

**Issue by xBLACKICEx** [siyuan-note/siyuan#5113]
### How to sync (third-party software) notes without changing the original storage location for Android 11+?

I personally plan to synchronize notes through [synthing ](https://syncthing.net/)but because Android 11 version after other software can not access the package folder, even if there are individual folder software to obtain permission from Google there is no great use (not all have to manually copy and paste synchronization?)

I also thought about syncing via symbol link, but one is that "Termux" has not yet obtained permission, and the other is that I tested it on my Android 10 phone and found that the default disk format of Android does not support symbol lnk, even if Termux obtains permission later, there is no point
![image](https://user-images.githubusercontent.com/51036094/172259904-ba062576-a7f4-4e4d-94df-bb8960d9a73b.png)

Android 10 now also has a form of synchronization by replacing the data, but what about Android 11? Sync software(App, cloud) almost refused to get Google's permission!

### 描述可能的最优解决方案 Describe the optimal solution

I hope the mobile side of Siyuan support custom folder storage as soon as possible! , otherwise it won't be able to do anything except root.

**Comment by 88250** [comment]
Siyuan Android uses private storage, and other applications have no way to read and write files.

If you want to use third-party synchronization software to synchronize data, you can consider fork https://github.com/siyuan-note/siyuan-android and then modify the code to specify the storage workspace path parameter when starting the kernel.

At present, we will not consider letting users set this parameter directly, because Siyuan may crash if other applications read and write data during operation.

We have closed this issue, thanks for the feedback.
