### ISSUE TITLE
API to get context for widget

### ISSUE THREAD

**Issue by lorefnon** [siyuan-note/siyuan#5190]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I am trying to create a custom widget for SiYuan. I am not sure how to get the current context of the widget eg. notebookId, blockId etc. which I can use for interacting with the kernel API and save the widget data. 

Is there already an API available for this ? 

Best I have found so far is `window.frameElement.parentElement.parentElement.dataset.nodeId` to get block id which does not seem ideal. 

Apologies if this has been discussed elsewhere. I am not familiar with Chinese so searching past issues is difficult for me. I was also looking into some of existing widgets but most don't seem to be open source (only minified sources are committed). 

### 描述可能的最优解决方案 Describe the optimal solution

A minimal solution is to include some query parameters which provide this information like `/widgets/testwidget?notebookId=xyz&blockId=xyz`.

Alternatively a global constant SiYuanContext could be injected into each widget frame context.

### 其他信息 Other information

Thanks for creating this application. I have just started using it and love it so far. Thanks for your help in advance.

**Comment by leolee9086** [comment]
just as you found，by now , mostly used way in my case was `window.frameElement.parentElement.parentElement.dataset.nodeId` to get those context.

and ,if there must be something add to widgets by siyuan app to provide some context,  I think url paremeters maybe a better solution,   because some widgets I  made  was just  designed to run standalone as a webapp. that way ,i can use same methods in browser and app to tell the widget what to do,

but I  also think ,   `window.frameElement.parentElement.parentElement` is just ennough for me.   it works fine  .

**Comment by 88250** [comment]
`window.frameElement.parentElement.parentElement.dataset.nodeId` should be the only solution so far. Maybe consider wrapping extraction as a function.

Thanks for the discussion.
