### ISSUE TITLE
Use `Endpoint` for network connectivity checks when syncing

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7805]
https://ld246.com/article/1679415411233

**Comment by aptexd** [comment]
Pony : 说个数吧，把 qq.com 也给我加上去

**Comment by mozhux** [comment]
这个英文描述就很国际化
This English description is very international

**Comment by SineMark2020** [comment]
其实标题最好的做法是中英并列，就可满足中英需求，内容就看谁提出的就用什么语言讨论，也不用花太多时间，就只是标题长了点.

**Comment by AugustTuan** [comment]
建议可以设置为中英双语。
翻译以后的界面并不友好
![0)7VW}@J1F}X(}{E )B(`OS](https://user-images.githubusercontent.com/37429029/228427182-4ae6f028-1a47-420c-95d3-a609ea81bad3.jpg)

**Comment by 88250** [comment]
@SineMark2020 @AugustTuan Please refer to https://github.com/siyuan-note/siyuan/issues/7814#issuecomment-1487953082

**Comment by SineMark2020** [comment]
@88250  I think you might be right. There are already QQ and ld246 for the Chinese community. For English users there needs to be an English community. But Github is a not good discussion forum, Reddit may be the more suitable place. Because all issues on github will be closed, it is not suitable for publishing teaching articles and using tips. thanks.

**Comment by 88250** [comment]
@SineMark2020 Yes, GitHub Issues it not for discussion, here are our plan https://github.com/siyuan-note/siyuan/issues/7758#issuecomment-1487885962.
