### ISSUE TITLE
Allow using formatting, links and embeds within "Memo"

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7870]
### In what scenarios do you need this feature?

I am a researcher and this means that I am reading many articles. I often highlight a specific passage and write a note. This is already possible in SiYuan thanks to Memo, but I can write just a very simple info.

![image](https://user-images.githubusercontent.com/63197393/229595152-b29dd8f0-2b20-42d5-be0c-9212efdededa.png)

 It would be great if this was expanded so I could use it for full comments. Thanks to internal links and tags, I could then very easily find these comments through backlinks. 

 

### Describe the optimal solution

Ideally, Memo would allow for the same features as the normal page, this includes:
- links (internal)
- tags
- formatting
- embeds

### Describe the candidate solution

I would appreciate if there was at least a possibility to use links and tags within memos. Already this would very simplify my work.

**Comment by 88250** [comment]
Hello, the inline memo feature is designed to only support plain text. If you need other inline-level typography elements, please use block quotes.

**Comment by zxhd863943427** [comment]
It didn't has direct way to do this, because memo is designed to plain text. But so theme has feature to solve, it look like:
![图片](https://user-images.githubusercontent.com/74853597/229657116-7bf117a9-ea15-476b-a147-a8ca25fd249b.png)

This is not the most satisfying approach, but it is the method currently available, and the community is working on ways to make this feature independent of the theme

**Comment by ciceronianus** [comment]
Block reference? However, where would be that block? This seems to be a very complicated and impractical solution, unfortunately. Memo that would allow links, could be used also for commenting in the multiplayer use.
