### ISSUE TITLE
If there is a page with the same name, inform the user and suggest merging them

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7968]
### In what scenarios do you need this feature?

It happens to me that sometimes I create a page that already exists. In such cases, it would be great to get some information on this fact / warning and maybe a suggestion to merge them. 

![image](https://user-images.githubusercontent.com/63197393/231514434-946383cc-1c1e-4bb4-9e72-77c8b1de35cb.png)

### Describe the optimal solution

If a page with the same name exists, provide some type of an idicator. This indicator can have different forms. It can be a small warning "!" or something completely different.

![image](https://user-images.githubusercontent.com/63197393/231514705-35477c6e-b34b-4587-a0de-dec3d1ad5fc6.png)

Give then the user an ability to merge pages.

**Comment by 88250** [comment]
Hello, we don’t think it is necessary to remind users to merge when creating documents with the same name, because there may be a lot of duplicate names when used based on the document tree. For example, the parent document is different, but the child may be named "Overview", so Merging is best done manually.

By the way, SiYuan has a transfer reference function (the function entry will only appear under the block icon menu of the document block when the document is referenced), which can transfer all references from one document to another document.

![image](https://user-images.githubusercontent.com/873584/231617033-c1002b2c-0906-4840-a4e2-3cdf768699c7.png)

**Comment by ciceronianus** [comment]
So how the user can easily find that there are other documents of the same name? An easily merge them?

**Comment by 88250** [comment]
At present, we can only rely on manual search or memory to determine whether there is a document with the same name.

**Comment by ciceronianus** [comment]
I think there should be probably some solution to this problem in future because this current situations is quite cumbersome. 
In note-taking apps, some of the most important actions are related to organisation: moving, merging, splitting etc. Ability to see that some note already exists somewhere, is crucial here.
