### ISSUE TITLE
Widgets in Bazaar: Add "English" label to help international users

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7971]
### In what scenarios do you need this feature?

One of the problem for international users is that many widgets are in Chinese only. It is also confusing. 
I suggest to add "English" label (or similar) to widgets that support English and that would be visible already in the overview of widgets with possible filtering.

![image](https://user-images.githubusercontent.com/63197393/231563334-233e1075-1145-4d1d-a185-1e79c4c5b8cf.png)

### Describe the optimal solution

Add something like "English" label to widgets supporting English. 

### Describe the candidate solution

Add something like "English supported" at least to the description of widgets.

**Comment by nhan000** [comment]
I suggest 2 things here to make it more inline with other note-taking apps: Change "Bazaar" to "Marketplace" and "Widgets" to "Plugins".  It's a minor thing for sure, but it does improve international user experience a lot.

**Comment by 88250** [comment]
It's not easy, and that's the price of being different. Some people may think that the author of SiYuan is a very stubborn person. Since he knows that this word is difficult for users to understand and will cause inconvenience in promotion, he still uses it...

Nethernoreless, I insist on using the word all the time, like some kind of fanatical believer 😈

**Comment by nhan000** [comment]
haha I had a hunch that you're very meticulous and have put lots of thought into the word you chose. Anyway, a compromise I can think of is still change to "Marketplace" and in the documentation (the English User Guide) you have a section for Marketplace that you can write a story about the origin of Marketplace, such as "Initially Marketplace was called "Bazaar", inspired by the book [The Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar), to pay tribute to and continue the tradition of open-source software development".

This is just my personal experience: When I first opened the setting panel of SiYuan I didn't even click into Bazaar because it sounds... bizarre (both how you pronounce and the feeling I had at that time). I'm not being disrespectful here. It just that I had no idea what it is because I never encounter the word "bazaar" outside of its original meaning of "an area of small shops and people selling things, especially in South Asia, North Africa, or the Middle East", usually seen in text about tourism in these areas (I grew up in a South East Asian country and over there the English word is just "market" or "wet market"). I would never have thought that it has anything to do with software development and more like a "loss-in-translation" from Chinese to English. I think you'd agree that users won't know your intention anyway unless they ask you directly so I don't know if using "Bazaar" would accomplish what you wanted to. Having a good open-source software like SiYuan is the best way to carry the tradition forward.

Speaking of translation here it's also good to a line in the Readme explaining what "SiYuan" means. I heard someone said about "simple note" but I'm not sure?

**Comment by Mrxiang-Plus** [comment]
哈哈哈，D大还是很关心老外的意见

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/8177 will support i18n settings, but we need marketplace package developers to adapt it.
