### ISSUE TITLE
Content type filtering when inserting reference links via `((`, `[[`

### ISSUE THREAD

**Issue by TonyAtlas** [siyuan-note/siyuan#8009]
### In what scenarios do you need this feature?

Entering "((" or "[[" always displays the same list of suggested links to pages and different blocks.

In order not to duplicate the symbol functionality and to create additional flexibility and quick search when selecting reference links, you can set to output different types of data depending on the characters you enter.

In about 80% of the cases I need to insert pages reference links rather than data blocks links. But when I enter any of the character choices I get all types of information and it is often very inconvenient to look up pages in the list because of the large amount of blocks along with them.

Breaking up the output of information types with "((", "[[" would make searching cleaner and much easier, especially in large workspaces.

### Describe the optimal solution

Maybe you can see better how exactly you can divide the search for information by characters. The main thing is to have this separation, since the output itself works through all 2 types of characters ("((", "[[")).

But it could look like this:

"((" - The normal version of the extradition, the one we have now. That is, when all types of data are shown.

"[[" - Output only pages reference links. (What is missing most of all in my opinion).

"{{" - For flexibility, if it's not hard to implement, you could let the user choose what type of information to output for these characters. I.e. it is a menu, similar to the output filter in the search box.

But this is the maximum wish. The most important thing in my opinion to have the ability to separately obtain in the output reference page links without any blocks.

**Comment by HowcanoeWang** [comment]
一些背景信息 | Some background information

![image](https://user-images.githubusercontent.com/19968935/232357906-c154fa37-0e32-4ef3-82aa-42dae81b0144.png)

可以在设置中选择显示的类型 | And type filters when searching in the setting

![image](https://user-images.githubusercontent.com/19968935/232357755-e8ec33ac-38fa-4c62-9729-7751229b4df7.png)

但是我确实同意应该在搜索中提供类型过滤的快捷键，但是不是使用不同的起手符号来区别(为了兼容不同软件之间共同的快捷键)，个人更喜欢使用关键字/符号来开启类型过滤

But I do agree that need some quick filters in the search function, but instead of using different start symbols (Compatible with commonly used shortcuts from other note software), personally prefer using keywords or symbols to filter tyes.

E.g.:

`(( text text :h3`  来过滤三级标题

`(( text text :h3`  to filter types of heading 3

![image](https://user-images.githubusercontent.com/19968935/232358509-76c47f10-f0e5-4315-b765-e34449f25435.png)

**Comment by TonyAtlas** [comment]
Thank you for correcting my suggestion and sharing the information.

Your filtering option is only convenient if the person writes in English. 

For example, I write in another language. This means that, for example, in order to start looking for reference links only among notes (and not blocks), I have to switch to English first, enter this letter, then switch back to my language and already write in it what I'm looking for.

Add to this that we also enter a number of characters in addition to this letter: "((:"

It turns out a bit complicated construction, and not at all inconvenient for those who write in languages other than English. 

Your version can be used if you create in the settings the possibility for each user to assign its own symbol in its own language for each type of information.

My version is not as accurate, but very easy to type.

Also, in my case I usually don't remember what type of block I need when specifying a reference (list, paragraph, quote, etc.), but I usually always remember whether it's a block or a page. 
So in my opinion this is a more important and global distinction than between block type

**Comment by 88250** [comment]
For a long time, `[[` actually exists only as a more convenient key (without pressing <kbd>Shift</kbd>), the reason why we did not consider filtering only document blocks is because we want to keep all blocks on an equal footing, This design can achieve better consistency.

But in terms of actual use, as you mentioned above, it is possible to ref document blocks in most usage scenarios, so it should be more sensible to give up some design consistency for better convenience.

Thanks your proposal.

**Comment by ciceronianus** [comment]
Just on the use of `[[` as a more conveient key than `((` . I think this is pretty dependent from the keyboard layout. E.g., in Czech, `[[` is more difficult to type than `((`, because the former requires AltGr key, while the latter only shift key. 

This is just a reminder how relative is what is easy to type :).

**Comment by 88250** [comment]
@HowcanoeWang It is actually not easy to search for overly detailed types, such as the h3 filter you mentioned. In fact, before searching, we have a high probability of not knowing whether we can hit on this detailed type.

**Comment by HowcanoeWang** [comment]
Any use examples or illustrations for this updates? feels no difference between (( and [[ in the latest version

**Comment by 88250** [comment]
@HowcanoeWang `[[` just search for doc blocks, `((` search for all types of blocks.

**Comment by HowcanoeWang** [comment]
related CN forum link: https://ld246.com/article/1681874537098

> @TonyAtlas 
> Your filtering option is only convenient if the person writes in English.
> 
> I write in another language. This means that, for example, in order to start looking for reference links only among notes (and not blocks), I have to switch to English first, enter this letter, then switch back to my language and already write in it what I'm looking for.

As Chinese user, siyuan can handle both EN : and CN ： at the same time, and no need to switch input lang for the symbol. And for most Chinese input, hitting `shift` will switch to EN mode at the same time, could you give more explanation for your lang input?

And another alternative option, is using `tab` as the block type filter rather than `:` symbol (but may conflict with #7995 )
