### ISSUE TITLE
"Optimize typography" could remove redundant formatting

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8050]
### In what scenarios do you need this feature?

This is a small, yet interesting issue. 
I have copied a text in italics into SiYuan:

![image](https://user-images.githubusercontent.com/63197393/233053666-cf26aaf8-b982-4d5f-aaf4-c7805a24206c.png)

When I copy it outside, it gets the following formatting:

![image](https://user-images.githubusercontent.com/63197393/233053542-b788e834-cc6a-4162-892b-ed8fa2fe1463.png)

Note the superfluous use of `* *`.

### Describe the optimal solution

I would suggest that "optimize typography" should take care of these cases:
![image](https://user-images.githubusercontent.com/63197393/233053816-7ec2ea06-2ee9-470c-b5ed-d7ac0fc72c77.png)

I.e., it would spot places where there are only blank space between the ending `*` and starting `*` and it would remove thus both `*` without any detriment to the formatted text. 

This is just a suggestion.

**Comment by zxhd863943427** [comment]
There is a high probability that this idea cannot be realized, because currently optimized typesetting can only be optimized for unambiguous decisions: for example, adding spaces, and other processing of formats may cause troubles for different users.

For your case, it is recommended to use "paste escaped text"

**Comment by 88250** [comment]
@zxhd86394342 is right, we closed this issue, thank you.
