### ISSUE TITLE
改善PDF文本标注使其更整齐

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8213]
### In what scenarios do you need this feature?

思源：
![image](https://user-images.githubusercontent.com/125173405/236991949-6ef2b541-abe6-4287-b3a5-ba69f8928083.png)
![image](https://user-images.githubusercontent.com/125173405/236992258-fa14f6be-7541-409a-912e-ab2934b82473.png)

Zotero：
![image](https://user-images.githubusercontent.com/125173405/236992015-f6dc9b88-697f-4dc4-a5ad-56ea29c18fe8.png)
![image](https://user-images.githubusercontent.com/125173405/236992295-a1e6028e-edcb-479b-bc6f-a4ee213e36e0.png)

如上图对比所示，当思源遇到这种字形大小不统一的时候建立的标注非常的参差不齐，而Zotero的就相对整齐。
还有一个问题是划选和实际建立批注的效果似乎不太一样：
思源：
![PluginTask_oAibMO1T44](https://user-images.githubusercontent.com/125173405/236992528-1203d10f-fd2c-47f8-9f4b-767a0c11b700.gif)
Zotero：
![zotero_WjSrdm9M5d](https://user-images.githubusercontent.com/125173405/236992599-50f2c450-655d-4e98-845b-2e086783c99a.gif)
这点要是也能向Zotero看齐就更好了。

### Describe the optimal solution

希望能改进文本划选质量使其更整齐。

**Comment by stonecutter-21** [comment]
+1，如果单词间距较大也会断开，比较影响外观
<img width="684" alt="截屏2023-05-09 18 50 02" src="https://github.com/siyuan-note/siyuan/assets/72546433/27bf8306-1d0f-4de0-b7da-cddff8a9e93c">

**Comment by stonecutter-21** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: D ***@***.***&gt;
发送时间: 2023年5月9日 20:55
收件人: siyuan-note/siyuan ***@***.***&gt;
抄送: Lin ZhenYi ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [siyuan-note/siyuan] 改善PDF文本标注使其更整齐 (Issue #8213)





 
两位方便的话请将 PDF 发送给我试下 ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							1.pdf 							 (10.0MB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=cdc83736130cef57ffbb4f36336463628baac13631646362171819425254010054074c05095c004f075152071c510001531a5754060501070b565252025c6662031911525770be235958979d401ebf511625b14912a8892a5c3e&key=cdc83736130cef57ffbb4f36336463628baac13631646362171819425254010054074c05095c004f075152071c510001531a5754060501070b565252025c6662031911525770be235958979d401ebf511625b14912a8892a5c3e&code=27a61dcb&from=

**Comment by 88250** [comment]
收到，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 改善PDF文本标注使其更整齐 (Issue #8213)





 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: D ***@***.***&amp;gt; 
 发送时间: 2023年5月9日 20:55 
 收件人: siyuan-note/siyuan ***@***.***&amp;gt; 
 抄送: Lin ZhenYi ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [siyuan-note/siyuan] 改善PDF文本标注使其更整齐 (Issue #8213) 
 
 
 
 
 
   
 两位方便的话请将 PDF 发送给我试下 ***@***.*** 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
   
  	 
  	 		 			从QQ邮箱发来的超大附件 	 
  	 		 				 					 						 							 						 					 
  					 						 							1.pdf 							 (10.0MB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&amp;k=cdc83736130cef57ffbb4f36336463628baac13631646362171819425254010054074c05095c004f075152071c510001531a5754060501070b565252025c6662031911525770be235958979d401ebf511625b14912a8892a5c3e&amp;key=cdc83736130cef57ffbb4f36336463628baac13631646362171819425254010054074c05095c004f075152071c510001531a5754060501070b565252025c6662031911525770be235958979d401ebf511625b14912a8892a5c3e&amp;code=27a61dcb&amp;from=

**Comment by Vanessa219** [comment]
我们使用的是 pdf.js, https://mozilla.github.io/pdf.js/web/viewer.html 官网上划选也是无法对齐。

**Comment by chenshinshi** [comment]
> 我们使用的是 pdf.js, https://mozilla.github.io/pdf.js/web/viewer.html 官网上划选也是无法对齐。

我想细问一下目前pdf划线批注复制的缺斤少两问题也是pdf.js的问题吗？
Zotero
![image](https://github.com/siyuan-note/siyuan/assets/125173405/596a609c-a1aa-4acb-832e-7d80d9d07dbc)
思源
![image](https://github.com/siyuan-note/siyuan/assets/125173405/33243b73-4b6c-4459-804c-13f31923af59)
这个问题非常容易触发，经常划线部分的前后会缺斤少两，不知道与pdf自身格式有无关系，但是在zotero的表现还是不错的。

**Comment by Vanessa219** [comment]
可以把 pdf 上传到官网  https://mozilla.github.io/pdf.js/web/viewer.html  划选后复制再粘贴出来看看。如果官方解决了，我们这里会进行跟进的。
