### ISSUE TITLE
反链条目重复

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我的情况：
https://github.com/siyuan-note/siyuan/assets/125173405/770c0ca3-1b89-438e-9a2a-6d24d126857d
导出成sy.zip再导入后重复条目消失了。重建索引、最优化排版后还存在重复条目。

群友的情况：
![95e1e5b41ac21e1ee370742e749340e5](https://github.com/siyuan-note/siyuan/assets/125173405/a46c6d49-1e43-4faa-8f3e-fae14b5760b7)

### Expected result

希望找出原因修复重复条目

### Version environment

```markdown
- Version: 2.9.3dev4
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
试下重建索引



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月27日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 反链条目重复 (Issue #8630)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
我的情况：
 https://github.com/siyuan-note/siyuan/assets/125173405/770c0ca3-1b89-438e-9a2a-6d24d126857d
 导出成sy.zip再导入后重复条目消失了。重建索引、最优化排版后还存在重复条目。
 
群友的情况：
 
 
Expected result
 
希望找出原因修复重复条目
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version: 2.9.3dev4 - Operating System:  - Browser (if used):
 
Log file
 
无需
 
More information
 
No response

**Comment by chenshinshi** [comment]
> 试下重建索引
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月27日(周二) 下午4:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [siyuan-note/siyuan] 反链条目重复 (Issue #8630) Is there an existing issue for this? I have searched the existing issues Can the issue be reproduced with the default theme (daylight/midnight)? I was able to reproduce the issue with the default theme Could the issue be due to extensions? I've ruled out the possibility that the extension is causing the problem. Describe the problem 我的情况： https://github.com/siyuan-note/siyuan/assets/125173405/770c0ca3-1b89-438e-9a2a-6d24d126857d 导出成sy.zip再导入后重复条目消失了。重建索引、最优化排版后还存在重复条目。 群友的情况： Expected result 希望找出原因修复重复条目 Screenshot or screen recording presentation No response Version environment - Version: 2.9.3dev4 - Operating System: - Browser (if used): Log file 无需 More information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

才发现文档重建索引和数据历史重建索引不是一回事，通过文档树重建索引后重复条目消失
