### ISSUE TITLE
Add message prompts for successful copy and cut

### ISSUE THREAD

**Issue by StarDustSheep** [siyuan-note/siyuan#8792]
为各种复制和剪贴的操作加上已操作的信息提示

### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/114859111/11e58edb-89e6-4b71-b1fd-6d1cff6c0a67)

![image](https://github.com/siyuan-note/siyuan/assets/114859111/880eab0c-f119-4457-96eb-f42986d3b36a)

在思源的复制中，有很多种类型，而常用的有复制整个块、复制为引用块、复制为纯文本，其他种类的复制也是有人使用的。
然而，由于复制操作的复杂多样，以及有时各种原因的未成功复制想要的块的想要的内容（比如光标位置错误、电脑其他进程的卡顿导致快捷键失效、输入法导致的快捷键失效），使得复制操作体验并不是很好。
比如我个人，经常使用ctrl+shift+C来复制为引用块，但由于工作单位的电脑键盘手感不是很好（老的薄膜键盘），总是不确定自己是否正确地按出了快捷键。
我建议为这些复制操作和剪贴操作加上成功后的message以提示用户自己完成了这个操作。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/114859111/d13e2fe8-bde9-4758-aaf5-89ede9701f1f)
![image](https://github.com/siyuan-note/siyuan/assets/114859111/b7b67331-95b4-466d-a77a-46654e27f1bb)
在完成各种复制操作，还有剪贴操作的时候，在右上角跳出信息提示
* 已复制为块引用
* 已复制为嵌入块
* 已复制块超链接
* 已复制……
* 已重复块
* 已剪切块

用户多选块的时候，只能做这几个复制操作和剪贴，对应的信息提示也要有区别
![image](https://github.com/siyuan-note/siyuan/assets/114859111/2a4550ed-63dc-4478-80b1-e202bd883a04)
* 已复制多个块
* 已复制多个块纯文本
* 已复制多个块 文本*
* 已重复多个块
* 已剪切多个块

或者把“多个块”换成“选中的多个块”

这样能给用户更明确的操作反馈，减少用户使用快捷键和更多复制操作时的不确定感和摩擦力。

**Comment by zazuone** [comment]
> 这样频繁弹出感觉过于干扰用户了。

可以加一个开关，让用户自主决定是否需要显示拷贝成功的提示。

**Comment by StarDustSheep** [comment]
> 这样频繁弹出感觉过于干扰用户了。
可以加上后先看看反馈，复制和剪贴并不是粘贴这种可能会几秒内按很多次的操作

**Comment by 88250** [comment]
再等等看看 issue 讨论。

**Comment by cwxsss** [comment]
不建议添加提醒，我觉得太干扰了，复制一般使用快捷键或者鼠标右键，添加提示的意义不大

**Comment by suka233333** [comment]
个人建议添加提醒，有一个反馈，会有正向的奖赏作用，会让用户使用功能更有成就感。
当然，也可以在提醒中加入按钮，一键关闭此类型通知，即可两全其美，类似于这种超链接按钮
![image](https://github.com/siyuan-note/siyuan/assets/115850846/dd89dc82-c4ae-45cc-8355-fb703ea155db)

**Comment by zxkmm** [comment]
I don’t like this design. There’s no software or OS in the world that “do remind” when user copied something, it’s too disturbing. Personally I think if your keyboard broken, just change the keyboard, because apparently even if you implemented this change to SiYuan, you’ll still face same issue on other all apps or even Windows file manager itself, it’s not elegant that this part been done by a note taking app.
however I think if many people like this, maybe Just quickly flash the copied text (or a frame around the text) one or two times as an optional remind.

**Comment by Vanessa219** [comment]
鉴于大部分软件都没有类似的功能，如果加上大的话，可能会对部分用户造成干扰，我们就先关闭了。
