### ISSUE TITLE
思源用户社区国内虚拟运营商手机号码无法注册

### ISSUE THREAD

**Issue by pengcheng820** [siyuan-note/siyuan#8923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源用户社区国内虚拟运营商手机号码无法注册，号码已真实使用近八年

![image](https://github.com/siyuan-note/siyuan/assets/12994898/a276139f-4ed4-4e22-9ca7-794f7f6419e9)

![image](https://github.com/siyuan-note/siyuan/assets/12994898/d53f134e-0ceb-4672-90b8-6d5b50b8e53f)

### Expected result

支持虚拟运营商号码注册

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
这个是故意屏蔽的，我们主要顾虑是放开以后会产生大量推广内容。


请保持该 issue 打开，我们还需要考虑一下，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 晚上6:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 思源用户社区国内虚拟运营商手机号码无法注册 (Issue #8923)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
思源用户社区国内虚拟运营商手机号码无法注册，号码已真实使用近八年
 

 

 
Expected result
 
支持虚拟运营商号码注册
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version:  - Operating System:  - Browser (if used):
 
Log file
 
1
 
More information
 
No response

**Comment by 88250** [comment]
目前已经支持虚拟运营商号段注册，感谢反馈。
