### ISSUE TITLE
Ctrl+Shift+G shortcut key to switch to read-only mode fails

### ISSUE THREAD

**Issue by CodeYiShu** [siyuan-note/siyuan#9255]
2.10.6版本ctrl+e读写切换失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

2.10.6版本ctrl+e读写切换失效
快捷键没有了ctrl+e，就算用ctrl+shift+G也不能用，很不方便

### Expected result

ctrl+e可以读写切换

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by 88250** [comment]
请检查快捷键是否被其他软件占用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月23日(周六) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 2.10.6版本ctrl+e读写切换失效 (Issue #9255)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
2.10.6版本ctrl+e读写切换失效
 快捷键没有了ctrl+e，就算用ctrl+shift+G也不能用，很不方便
 
Expected result
 
ctrl+e可以读写切换
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version:  - Operating System:  - Browser (if used):
 
Log file
 
.
 
More information
 
No response

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by 88250** [comment]
关联 https://ld246.com/article/1695275827685

**Comment by 88250** [comment]
已经从论坛中获取了能够重现问题的数据集，我们排查下看看。

**Comment by Vanessa219** [comment]
由于单篇文档的只读优先级高于全局设置，因此单独设置过文档的，再设置全局就会无效。可以先把文档的只读模式设置成默认的，这样就可以使用全局的。

<img width="416" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/78098790-5ad5-4e8d-8f96-9080eb6f6aea">

**Comment by CodeYiShu** [comment]
@Vanessa219 感谢 设置成默认的就可以了
