### ISSUE TITLE
The access authorization code command line parameter must be set when deploying via Docker

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9328]
强制使用鉴权码代码带来的的初次创建 docker 服务后的死锁问题

### In what scenarios do you need this feature?

我遇到了一个问题，使用dockor创建思源的服务。初次打开url访问思源，提醒我要设置鉴权码。

但是由于我无法进入思源的UI界面，所以没法在软件里设置健全码——死锁了。

虽然说可以让用户进入docker的命令行界面，改里面的配置文件。但是如果要把这个作为一个常规方案，那就太离谱了

### Describe the optimal solution

如果没有设置鉴权码就随机生成一串字符串，然后让用户一个一个输进去（禁用拷贝）。

这样除非用户是什么抖 M，否则为了避免麻烦自然会记得去设置鉴权码。

**Comment by 88250** [comment]
Docker 部署估计要把这个参数调整为强制项，缺失该参数则启动报错。另外，设置界面中移除访问授权码的配置项，仅支持启动命令配置，这样就一致了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月1日(周日) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 强制使用鉴权码代码带来的的初次创建 docker 服务后的死锁问题 (Issue #9328)




 
In what scenarios do you need this feature?
 
我遇到了一个问题，使用dockor创建思源的服务。初次打开url访问思源，提醒我要设置鉴权码。
 
但是由于我无法进入思源的UI界面，所以没法在软件里设置健全码——死锁了。
 
虽然说可以让用户进入docker的命令行界面，改里面的配置文件。但是如果要把这个作为一个常规方案，那就太离谱了
 
Describe the optimal solution
 
如果没有设置鉴权码就随机生成一串字符串，然后让用户一个一个输进去（禁用拷贝）。
 
这样除非用户是什么抖 M，否则为了避免麻烦自然会记得去设置鉴权码。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by frostime** [comment]
> Docker 部署估计要把这个参数调整为强制项，缺失该参数则启动报错。另外，设置界面中移除访问授权码的配置项，仅支持启动命令配置，这样就一致了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月1日(周日) 晚上10:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [siyuan-note/siyuan] 强制使用鉴权码代码带来的的初次创建 docker 服务后的死锁问题 (Issue #9328) In what scenarios do you need this feature? 我遇到了一个问题，使用dockor创建思源的服务。初次打开url访问思源，提醒我要设置鉴权码。 但是由于我无法进入思源的UI界面，所以没法在软件里设置健全码——死锁了。 虽然说可以让用户进入docker的命令行界面，改里面的配置文件。但是如果要把这个作为一个常规方案，那就太离谱了 Describe the optimal solution 如果没有设置鉴权码就随机生成一串字符串，然后让用户一个一个输进去（禁用拷贝）。 这样除非用户是什么抖 M，否则为了避免麻烦自然会记得去设置鉴权码。 Describe the candidate solution No response Other information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

docker 启动强制添加授权码参数可以理解。

不过「设置界面中移除访问授权码的配置项」应该仅仅指的是 docker 启动的时候显示的设置项目吧？

**Comment by 88250** [comment]
嗯，仅是 Docker 浏览器端移除这个配置项。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月2日(周一) 中午12:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 强制使用鉴权码代码带来的的初次创建 docker 服务后的死锁问题 (Issue #9328)




  
Docker 部署估计要把这个参数调整为强制项，缺失该参数则启动报错。另外，设置界面中移除访问授权码的配置项，仅支持启动命令配置，这样就一致了。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年10月1日(周日) 晚上10:57 收件人: @.&gt;; 抄送: @.&gt;; 主题: [siyuan-note/siyuan] 强制使用鉴权码代码带来的的初次创建 docker 服务后的死锁问题 (Issue #9328) In what scenarios do you need this feature? 我遇到了一个问题，使用dockor创建思源的服务。初次打开url访问思源，提醒我要设置鉴权码。 但是由于我无法进入思源的UI界面，所以没法在软件里设置健全码——死锁了。 虽然说可以让用户进入docker的命令行界面，改里面的配置文件。但是如果要把这个作为一个常规方案，那就太离谱了 Describe the optimal solution 如果没有设置鉴权码就随机生成一串字符串，然后让用户一个一个输进去（禁用拷贝）。 这样除非用户是什么抖 M，否则为了避免麻烦自然会记得去设置鉴权码。 Describe the candidate solution No response Other information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
docker 启动强制添加授权码参数可以理解。
 
不过「设置界面中移除访问授权码的配置项」应该仅仅指的是 docker 启动的时候显示的设置项目吧？

**Comment by 88250** [comment]
考虑了下，只要是浏览器端就都移出这个配置项吧 https://github.com/siyuan-note/siyuan/issues/9331

毕竟浏览器端访问的主要场景是远程访问内核，这种情况无论是 Docker 部署还是其他方式部署的内核如果在浏览器端支持设置访问鉴权码会有安全隐患
