### ISSUE TITLE
虚拟引用提示「未找到 ID 为 xxx 的内容块」

### ISSUE THREAD

**Issue by Louie997** [siyuan-note/siyuan#9629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

鼠標移到虛擬引用上發現其中一個內容塊空白，提示「未找到 ID 为 xxx 的内容块」，如下圖
![image](https://github.com/siyuan-note/siyuan/assets/88768177/53398d50-9830-4d28-8deb-ace1fbc1d084)

![image](https://github.com/siyuan-note/siyuan/assets/88768177/9896d7a5-9545-47f7-89b8-6aabf2ec36f7)

我對這個內容塊有點印象，似乎是我之前的刪除過的，但是現在重建索引也無法解決。

### Expected result

不提示「未找到 ID 为 xxx 的内容块」

### Screenshot or screen recording presentation

如上

### Version environment

```markdown
- Version: v2.10.14
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13324241/system-log.zip)

**Comment by 88250** [comment]
所有笔记本打开，然后重建索引，等后台索引任务完毕以后搜索这个 ID 试试，如果搜不到那就是已经不存在了，这种情况下虚拟引用还会提示吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 虚拟引用提示「未找到 ID 为 xxx 的内容块」 (Issue #9629)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 
鼠標移到虛擬引用上發現其中一個內容塊空白，提示「未找到 ID 为 xxx 的内容块」，如下圖
 
 
 
我對這個內容塊有點印象，似乎是我之前的刪除過的，但是現在重建索引也無法解決。
 
Expected result
 
不提示「未找到 ID 为 xxx 的内容块」
 
Screenshot or screen recording presentation
 
如上
 
Version environment
 - Version: v2.10.14 - Operating System: win11 - Browser (if used):
 
Log file
 
system-log.zip
 
More information
 
No response

**Comment by Louie997** [comment]
所有笔记本打开，然后重建索引後，搜索 ID 已經搜不到了，但還是會有空白的情況，以及提示「未找到 ID 为 xxx 的内容块」

**Comment by 88250** [comment]
是否方便发一下所有数据（不需要 assets）给我们测试看看 845765@qq.com

**Comment by Louie997** [comment]
所有数据的話不太方便，有些比較私人。

不過我記得那個找不到的内容块是一個文檔，文檔名是 path，
後來我把它刪了，然後把另一個文檔的別名追加了 path，所以另一個文檔有被虛擬引用搜索到，就是下面紅框的部分。
![image](https://github.com/siyuan-note/siyuan/assets/88768177/4dfb81cd-b5fa-434c-ac84-26d36751799a)

現在把另一個文檔的別名中的 path 刪掉，就不會出現虛擬引用空白以及「未找到 ID 为 xxx 的内容块」的情況了。

**Comment by 88250** [comment]
我大概明白了，删掉原文档 path 后可以试下 设置 - 编辑器 - 虚拟引用 开关，关闭后再打开，这样会清理虚引的缓存。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Louie997** [comment]
> 虚拟引用 开关，关闭后再打开，这样会清理虚引的缓存。
開關之後還是會有問題。

我把有可能有問題的部分數據發給你了，謝謝。

**Comment by 88250** [comment]
收到，稍后我们邮件联系，谢谢。
