### ISSUE TITLE
What kind of features will be PRO-only in the future?

### ISSUE THREAD

**Issue by drawtheliner** [siyuan-note/siyuan#9742]
### In what scenarios do you need this feature?

I'm currently happy with the free plan, as I don't need any of the Pro features (which currently are only two: search within assets and use of own cloud storage solution).

However I'm concerned that in the future a greater number of features will be limited to Pro users. If that's the case, I would consider getting Pro just as a precaution, while pricing is still not prohibitive.

I would however prefer to know beforehand what are your plans regarding this. What kind of features will be Pro-only in the future?

### Describe the optimal solution

-

### Describe the candidate solution

-

### Other information

-

**Comment by Wetoria** [comment]
I think the most thing is let people know which feature will add.
User can purchase some feature perpetual like S3 and WebDAV. But someone maybe miss the activity time.
As a paid subscriber and a developer, I subscribed to support  the authors. but i regret missed the first 512 lifelong chance.

**Comment by Chenm4** [comment]
The previous explanation of the function of Pro is generally a cloud function, and the local function will remain free forever (but the local search for PDF resources unique to members has been added later, which I think is not the right decision, and the local function should always be implemented for free)

**Comment by Chenm4** [comment]
If the economic strength allows, you can buy pro to support the developer,Now there are still very few users,The developer doesn't have much income,I bought the pro but I haven't used the pro function,Just to support the developer,Or you can recommend this software like a friend,At present, there are still too few people who know about this software,It's difficult to establish a community ecology,Not to mention a plug-in community like obsidian

**Comment by 88250** [comment]
We hereby make a commitment that the existing free functions will not be charged in the future. If charged, they will only be limited to some functions that will be added in the future. However, so far, there is no specific plan for charging functions. If there is any, we will put it in [Roadmap](https://github.com/orgs/siyuan-note/projects/1).

Thank you for understanding our decision.

**Comment by zxhd863943427** [comment]
It's not a possibility but a certainty that more paid features will be added to the pro version as it's a matter of survival.

As you can see siyuan's current free plan is already quite feature rich and the pro features are relatively unattractive, which is favorable for users in the short term but not in the long term as the software may stop development due to lack of revenue. As an open source software that has no venture capital and does not survive on advertising or selling user data, the willingness and number of users to pay is effectively the length of its life.

What we all know is that there are only two ways to increase willingness to pay in general, cut the features and experience of the free program, and increase the features and experience of the PRO. siyuan in the case of unwillingness to do the former, then it is obvious that it can only do the latter. In terms of timing, the resource file search wasn't a scheduled program, it was purposely developed to increase the appeal of the pro version, but it still doesn't look appealing enough. If, as the user above said, he only subscribed to the pro version to support the official development, that's actually a failure, because the pro version should rely on higher attractiveness to win users' support.

Since the pro version's features are not cut from the free plan, perhaps you should rather see it as a paid official plugin, if that makes you feel better. Better than a regular plugin, your payment for this plugin directly supports the development of the open source project itself.
